name: Test + Zip publish
on:
  release:
    types: [created]
jobs:
  build:
    name: Create_package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt-hotspot'
          java-version: '11'
      - name: Maven
        run: mvn clean package "-DfunctionAppName=http-trigger-maven"
      - name: Make zip
        run: cd target/azure-functions/http-trigger-maven && zip -r http-trigger-maven.zip * -x local.settings.json
      - name: Rename zip
        run: mkdir target/upload & mv target/azure-functions/http-trigger-maven/http-trigger-maven.zip target/upload/${{env.RELEASE_VERSION}}.zip
      - uses: bacongobbler/azure-blob-storage-upload@v1.2.0
        with:
          source_dir: 'target/upload'
          connection_string: ${{ secrets.CONNECTIONSTRING }}
          container_name: 'templates/http-trigger-maven'
          extra_args: '--pattern *.zip'
          sync: false